//
//  SearchInteractor.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 6/21/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
    func fetchAppInfos(request: Search.FetchAppInfos.Request)
}

protocol SearchDataStore
{
    //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker = SearchWorker(appStore: AppsAPI())
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchAppInfos(request: Search.FetchAppInfos.Request)
    {
        worker.fetchOrders(completionHandler: { searchModels in
            print(searchModels)
        })
        
        let response = Search.FetchAppInfos.Response()
        presenter?.presentSomething(response: response)
    }
}
