//
//  SearchWorker.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 6/21/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker
{
    var appStore: AppStoreProtocol
    
    init(appStore: AppStoreProtocol)
    {
      self.appStore = appStore
    }
    
    func fetchOrders(keyword: String, completionHandler: @escaping ([SearchModel]) -> Void)
    {
      appStore.fetchOrders { (apps: () throws -> [SearchModel]) -> Void in
        do {
          let orders = try apps()
          DispatchQueue.main.async {
            completionHandler(orders)
          }
        } catch {
          DispatchQueue.main.async {
            completionHandler([])
          }
        }
      }
    }
}

protocol AppStoreProtocol
{
    func fetchOrders(completionHandler: @escaping (() throws -> [SearchModel]) -> Void)
}
