//
//  DetailInteractor.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/5/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
    func doSomething(request: Detail.Something.Request)
}

protocol DetailDataStore
{
    var appInfo: SearchModel? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
    
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    var appInfo: SearchModel?
    
    // MARK: Do something
    
    func doSomething(request: Detail.Something.Request)
    {
        worker = DetailWorker()
        worker?.doSomeWork()
        
        let response = Detail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
