//
//  ArcadeRouter.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/6/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ArcadeRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ArcadeDataPassing
{
  var dataStore: ArcadeDataStore? { get }
}

class ArcadeRouter: NSObject, ArcadeRoutingLogic, ArcadeDataPassing
{
  weak var viewController: ArcadeViewController?
  var dataStore: ArcadeDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ArcadeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ArcadeDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
