//
//  ArcadeInteractor.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/6/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArcadeBusinessLogic
{
  func doSomething(request: Arcade.Something.Request)
}

protocol ArcadeDataStore
{
  //var name: String { get set }
}

class ArcadeInteractor: ArcadeBusinessLogic, ArcadeDataStore
{
  var presenter: ArcadePresentationLogic?
  var worker: ArcadeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Arcade.Something.Request)
  {
    worker = ArcadeWorker()
    worker?.doSomeWork()
    
    let response = Arcade.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
