//
//  DetailInteractor.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/5/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
    func fetchAppInfo(request: Detail.AppInfo.Request)
}

protocol DetailDataStore
{
    var searchModel: SearchModel? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
    
    var presenter: DetailPresentationLogic?
    var searchModel: SearchModel?
    
    // MARK: Do something
    
    func fetchAppInfo(request: Detail.AppInfo.Request)
    {
        if let searchModel = searchModel {
            let response = Detail.AppInfo.Response(searchModel: searchModel)
            presenter?.presentAppInfo(response: response)
        }
    }
}
