//
//  DetailPresenter.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/5/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
    func presentAppInfo(response: Detail.AppInfo.Response)
}

class DetailPresenter: DetailPresentationLogic
{
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Do something
    
    func presentAppInfo(response: Detail.AppInfo.Response)
    {
        let model = response.searchModel
        let appIconDetailInfo = makeAppIconDetailInfo(model: model)
        let appInfoDetailInfo = makeAppInfoDetailInfo(model: model)
        let newFeatureInfo = makeNewFeatureInfo(model: model)
        let screenshotsPreviewInfo = makeScreenshotsPreviewInfo(model: model)
        let subtitleViewInfo = makeSubtitleInfo(model: model)
        let viewModel = Detail.AppInfo.ViewModel(
                appIconDetailInfo: appIconDetailInfo,
                appInfoDetailInfo: appInfoDetailInfo,
                newFeatureInfo: newFeatureInfo,
                screenshotsPreviewInfo: screenshotsPreviewInfo,
                subtitleInfo: subtitleViewInfo
        )
        viewController?.displayAppInfo(viewModel: viewModel)
    }
    
    private func makeAppIconDetailInfo(model: SearchModel) -> AppIconDetailView.Info {
        AppIconDetailView.Info(
            artworkUrl512: model.artworkUrl512,
            sellerName: model.sellerName,
            trackName: model.trackName
        )
    }
    
    private func makeAppInfoDetailInfo(model: SearchModel) -> AppInfoDetailView.Info {
        AppInfoDetailView.Info(
            userRatingCount: String(model.userRatingCount),
            averageUserRating: model.averageUserRating,
            contentAdvisoryRating: model.contentAdvisoryRating,
            trackContentRating: model.trackContentRating,
            genres: model.genres,
            artistName: model.artistName,
            languageCodesISO2A: model.languageCodesISO2A
        )
    }
    
    private func makeNewFeatureInfo(model: SearchModel) -> NewFeatureView.Info {
        NewFeatureView.Info(
            version: model.version,
            currentVersionReleaseDate: model.currentVersionReleaseDate
        )
    }
    
    private func makeScreenshotsPreviewInfo(model: SearchModel) -> ScreenshotsPreviewView.Info {
        ScreenshotsPreviewView.Info(
            images: model.screenshotUrls,
            imageSize: CGSize(width: 250, height: 500),
            type: .iphone
        )
    }
    
    private func makeSubtitleInfo(model: SearchModel) -> SubtitleView.Info {
        SubtitleView.Info(
            title: model.artistName,
            subtitle: "개발자"
        )
    }
}
