//
//  DetailPresenter.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/5/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
    func presentAppInfo(response: Detail.AppInfo.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentAppInfo(response: Detail.AppInfo.Response)
  {
    let viewModel = Detail.AppInfo.ViewModel()
    viewController?.displayAppInfo(viewModel: viewModel)
  }
}
