//
//  GameInteractor.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/6/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GameBusinessLogic
{
  func doSomething(request: Game.Something.Request)
}

protocol GameDataStore
{
  //var name: String { get set }
}

class GameInteractor: GameBusinessLogic, GameDataStore
{
  var presenter: GamePresentationLogic?
  var worker: GameWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Game.Something.Request)
  {
    worker = GameWorker()
    worker?.doSomeWork()
    
    let response = Game.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
