//
//  SearchPresenter.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 6/21/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentSomething(response: Search.FetchAppInfos.Response)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Search.FetchAppInfos.Response)
    {
        let displayedApps = response.apps.map { searchModel in
            return Search.FetchAppInfos.ViewModel.DisplayedApp(screenshotUrls: searchModel.screenshotUrls, artworkUrl512: searchModel.artworkUrl512, sellerName: searchModel.sellerName, trackName: searchModel.trackName)
        }
        let viewModel = Search.FetchAppInfos.ViewModel(displayedApps: displayedApps)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
