//
//  SearchModels.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 6/21/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  
  enum FetchAppInfos
  {
    struct Request
    {
        var keyword: String
    }
    struct Response
    {
        var apps: [SearchModel]
    }
    struct ViewModel
    {
        struct DisplayedApp
        {
          var screenshotUrls: [String]
          var artworkUrl512: String
          var sellerName: String
          var trackName: String
        }
        
        var displayedApps: [DisplayedApp]
    }
  }
}
