//
//  ListSearchRouter.swift
//  AppStoreClone
//
//  Created by jc.kim on 6/25/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListSearchRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ListSearchDataPassing
{
  var dataStore: ListSearchDataStore? { get }
}

class ListSearchRouter: NSObject, ListSearchRoutingLogic, ListSearchDataPassing
{
  weak var viewController: ListSearchViewController?
  var dataStore: ListSearchDataStore?
  
  // 코디네이터 패턴 연결을 위한 속성
  weak var coordinator: SearchCoordinator?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  // 앱 상세 화면으로 이동
  func routeToAppDetail(with appData: ListSearch.AppSearchResultDTO) {
    // 코디네이터가 있으면 코디네이터에 화면 전환 위임
    if let coordinator = coordinator {
      coordinator.showAppDetail(with: appData)
    } else {
      // 코디네이터가 없는 경우 기본 처리 (로그 출력)
      print("Warning: Coordinator not set in ListSearchRouter")
    }
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ListSearchDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
