//
//  ListSearchInteractor.swift
//  AppStoreClone
//
//  Created by jc.kim on 6/25/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListSearchBusinessLogic
{
  func doSomething(request: ListSearch.Something.Request)
}

protocol ListSearchDataStore
{
  //var name: String { get set }
}

class ListSearchInteractor: ListSearchBusinessLogic, ListSearchDataStore
{
  var presenter: ListSearchPresentationLogic?
  var worker: ListSearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListSearch.Something.Request)
  {
    worker = ListSearchWorker()
    worker?.doSomeWork()
    
    let response = ListSearch.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
