//
//  ListSearchPresenter.swift
//  AppStoreClone
//
//  Created by jc.kim on 6/25/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListSearchPresentationLogic
{
  func presentSomething(response: ListSearch.Something.Response)
}

class ListSearchPresenter: ListSearchPresentationLogic
{
  weak var viewController: ListSearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListSearch.Something.Response)
  {
    let viewModel = ListSearch.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
