//
//  TodayInteractor.swift
//  AppStoreSearch
//
//  Created by 도미닉 on 7/6/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodayBusinessLogic
{
  func doSomething(request: Today.Something.Request)
}

protocol TodayDataStore
{
  //var name: String { get set }
}

class TodayInteractor: TodayBusinessLogic, TodayDataStore
{
  var presenter: TodayPresentationLogic?
  var worker: TodayWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Today.Something.Request)
  {
    worker = TodayWorker()
    worker?.doSomeWork()
    
    let response = Today.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
